### ISSUE TITLE
path error

### ISSUE THREAD

**Issue by pinilorenzo** [MASILab/cornn_tractography#2]
Dear all,

thanks for your tool!
I’ve encountered some issues while running Singularity. 
According to the README file, once the .sif file is created, it can be executed by setting the parameters and paths. 
However, when I attempt to run the following code:

singularity run -e --contain \
     -B /home/brain/Desktop/data/T1.nii.gz \
     -B /home/brain/Desktop/data/ \
     -B /home/brain/Desktop/data/slant \
     -B /home/brain/Desktop/data/wml \
     --nv \
    /home/brain/Desktop/cornn_tractography/CoRNN_v1.0.0.sif \
    /data/T1.nii.gz \
    /data/output \ 
   --slant /data/slant \
   --wml /data/wml

I encounter the following error:
I’m also unclear about the second part of the code—specifically after /home/brain/Desktop/cornn_tractography/CoRNN_v1.0.0.sif \.

ERROR  : Failed to get real path of /var/lib/singularity/mnt/final/home/brain/Desktop/data/slant: No such file or directory
ABORT  : Retval = 255

I’ve tried using different paths and even creating data and slant folders inside /var/lib/singularity/mnt/final/. 
Unfortunately, I continue to encounter errors stating that directories or files cannot be found.

Any guidance or advice would be greatly appreciated!
Thanks

**Comment by GauravR1206** [comment]
Hello,
This is the latest version of the singularity, with details on how to execute it. Please try it out and let us know if you have any questions or encounter any issues.
https://github.com/yoonjongyeon/CoRNN_T1_tractography
